spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: aws-parameterstore:/cloud-member/prod/

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show-sql: true

management:
  endpoint:
    health:
      show-details: never

  endpoints:
    web:
      exposure:
        include: info

  info:
    env:
      enabled: true

info:
  app:
    team-name: ${TEAM_NAME}





















